import vx
import vx_builtins

builtins = [
    'quit',
    'suspend',
    'move_up_window',
    'move_down_window',
    'move_left_window',
    'move_right_window',
    'move_bol_window',
    'move_eol_window',
    'move_beg_window',
    'move_end_window',
    'save_window',
    'add_string_window',
    'backspace_delete_window',
    'backspace_window',
    'new_window',
    'delete_window',
    'attach_window',
    'attach_window_blank',
    'focus_internal_window',
    'redraw_all',
    'clear_window',
    'get_linecoloffset_of_str',
    'get_window_size',
    'get_ch_linecol_window',
    'get_str_linecol_window',
    'get_str_linecol_to_linecol_window',
    'get_linecol_window',
    'get_linecol_start_window',
    'set_linecol_window',
    'set_linecol_start_window',
    'print_string_window',
    'refresh_window',
    'resize_window',
    'move_window',
    'clear_contents_window',
    'get_contents_window',
    'set_color_window',
    'set_cursor',
    'rows',
    'cols',
    'line',
    'col',
]

for b in builtins:
    setattr(vx, b, getattr(vx_builtins, b))
